'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';

type PublicEquipment={company:{name:string;logoUrl:string|null};equipment:{assetCode:string;equipmentType:string;capacityBtu:number|null;technology:string|null;cycle:string|null;voltage:number|null;refrigerant:string|null;model:string|null;status:string;unit:string;environment:string|null}};
const labels:Record<string,string>={ACTIVE:'Ativo',MAINTENANCE:'Em manutenção',INACTIVE:'Inativo',REPLACEMENT_RECOMMENDED:'Substituição recomendada',REMOVED:'Removido'};
function publicBase(){const configured=(process.env.NEXT_PUBLIC_API_URL??'').trim().replace(/\/$/,'').replace(/\/api\/v1$/,'');return process.env.NODE_ENV==='production'?'/backend/public/equipment':`${configured||'https://solucenter-api-04bn.onrender.com'}/public/equipment`}
export default function EquipmentQrPage(){
 const {token}=useParams<{token:string}>();const[data,setData]=useState<PublicEquipment|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);fetch(`${publicBase()}/${encodeURIComponent(token)}`,{cache:'no-store'}).then(async r=>{const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.error?.message??'Equipamento indisponível.');return body}).then(body=>{if(active)setData(body)}).catch(err=>{if(active)setError(err.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[token]);
 return <main className="shell"><section className="hero"><div className="eyebrow">FICHA DO EQUIPAMENTO</div><h1>{data?.company.name??'SOLUCENTER'}</h1><p>Identificação técnica pelo QR Code</p></section><section className="card mobileCard" style={{marginTop:16}}>{loading&&<p>Carregando ficha…</p>}{error&&<div className="alert" role="alert">{error}</div>}{data&&<><div className="sectionTitle"><h2>{data.equipment.assetCode}</h2><span className="pill">{labels[data.equipment.status]??data.equipment.status}</span></div><div className="formGrid"><div className="field"><label>Equipamento</label><strong>{data.equipment.equipmentType}</strong></div><div className="field"><label>Capacidade</label><strong>{data.equipment.capacityBtu?`${data.equipment.capacityBtu.toLocaleString('pt-BR')} BTU/h`:'Não informada'}</strong></div><div className="field"><label>Modelo</label><span>{data.equipment.model??'Não informado'}</span></div><div className="field"><label>Tecnologia</label><span>{data.equipment.technology??'Não informada'}</span></div><div className="field"><label>Tensão</label><span>{data.equipment.voltage?`${data.equipment.voltage} V`:'Não informada'}</span></div><div className="field"><label>Fluido refrigerante</label><span>{data.equipment.refrigerant??'Não informado'}</span></div><div className="field"><label>Unidade</label><span>{data.equipment.unit}</span></div><div className="field"><label>Ambiente</label><span>{data.equipment.environment??'Não informado'}</span></div></div><p className="muted" style={{marginTop:20}}>Esta ficha pública não exibe endereço, contato do cliente ou dados internos de atendimento.</p></>}</section></main>;
}
