"use client";
import {useEffect,useMemo,useState} from 'react';
import {api} from '../../../lib/api';
import OsPhotoUpload from '../../../components/OsPhotoUpload';

export default function NovaOS(){
 const[step,setStep]=useState(1),[customers,setCustomers]=useState<any[]>([]),[materials,setMaterials]=useState<any[]>([]),[equipment,setEquipment]=useState<any[]>([]),[created,setCreated]=useState<any>(null);
 const[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const[f,setF]=useState<any>({customerId:'',unitId:'',environmentId:'',equipmentId:'',service:'CORRETIVA',priority:'NORMAL',reportedProblem:'',technicalDiagnosis:'',performedService:'',recommendations:'',finalValue:0,laborCost:0,travelCost:0,feesCost:0,otherCost:0,measurements:{},materialId:'',materialQty:1});
 useEffect(()=>{Promise.all([api('/customers'),api('/materials'),api('/equipment')]).then(([c,m,e]:any)=>{setCustomers(c);setMaterials(m);setEquipment(e)}).catch((e:any)=>setError(e.message))},[]);
 const customer=customers.find(x=>x.id===f.customerId);
 const unit=customer?.units?.find((x:any)=>x.id===f.unitId);
 const environments=unit?.environments??[];
 const availableEquipment=useMemo(()=>equipment.filter((x:any)=>x.customerId===f.customerId&&x.unitId===f.unitId&&(!f.environmentId||x.environmentId===f.environmentId)),[equipment,f.customerId,f.unitId,f.environmentId]);
 function set(k:string,v:any){setF((x:any)=>({...x,[k]:v}))}
 async function action(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e:any){setError(e?.message??'Não foi possível concluir esta etapa.')}finally{setBusy(false)}}
 async function createOS(){await action(async()=>{const os=await api('/service-orders',{method:'POST',body:JSON.stringify({customerId:f.customerId,unitId:f.unitId,environmentId:f.environmentId||undefined,equipmentId:f.equipmentId||undefined,priority:f.priority,reportedProblem:f.reportedProblem})});setCreated(os);await api(`/service-orders/${(os as any).id}/start`,{method:'POST',body:'{}'});setStep(3)})}
 async function saveTech(){await action(async()=>{if(Object.values(f.measurements).some(v=>v!==''&&v!=null))await api(`/service-orders/${created.id}/measurements`,{method:'POST',body:JSON.stringify(Object.fromEntries(Object.entries(f.measurements).filter(([_,v])=>v!==''&&v!=null).map(([k,v])=>[k,Number(v)])))});if(f.materialId)await api(`/service-orders/${created.id}/materials`,{method:'POST',body:JSON.stringify({materialId:f.materialId,quantity:Number(f.materialQty)})});setStep(4)})}
 async function complete(){await action(async()=>{await api(`/service-orders/${created.id}/complete`,{method:'POST',body:JSON.stringify({technicalDiagnosis:f.technicalDiagnosis,performedService:f.performedService,recommendations:f.recommendations,finalValue:Number(f.finalValue),laborCost:Number(f.laborCost),travelCost:Number(f.travelCost),feesCost:Number(f.feesCost),otherCost:Number(f.otherCost)})});const p:any=await api(`/service-orders/${created.id}/profitability`);alert(`OS concluída. Lucro: R$ ${p.profit.toFixed(2)} · Margem: ${p.margin}%`);location.href='/'})}
 return <main className="shell"><h1>Nova Ordem de Serviço</h1>{error&&<p className="error" role="alert">{error}</p>}<div className="steps">{[1,2,3,4].map(n=><div className={'step '+(step===n?'active':'')} key={n}>{n} · {['Cliente','Serviço','Atendimento','Finalizar'][n-1]}</div>)}</div>
 {step===1&&<div className="card"><h2>1. Cliente e local</h2><div className="field">Cliente<select value={f.customerId} onChange={e=>setF((x:any)=>({...x,customerId:e.target.value,unitId:'',environmentId:'',equipmentId:''}))}><option value="">Selecione</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field">Unidade<select value={f.unitId} onChange={e=>setF((x:any)=>({...x,unitId:e.target.value,environmentId:'',equipmentId:''}))}><option value="">Selecione</option>{customer?.units?.map((u:any)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></div><div className="field">Ambiente<select value={f.environmentId} onChange={e=>setF((x:any)=>({...x,environmentId:e.target.value,equipmentId:''}))}><option value="">Não informado</option>{environments.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="field">Equipamento<select value={f.equipmentId} onChange={e=>set('equipmentId',e.target.value)}><option value="">Não informado</option>{availableEquipment.map((x:any)=><option value={x.id} key={x.id}>{x.assetCode} · {x.equipmentType}</option>)}</select></div><button className="btn" disabled={!f.customerId||!f.unitId} onClick={()=>setStep(2)}>Próximo</button></div>}
 {step===2&&<div className="card"><h2>2. Serviço</h2><div className="field">Tipo<select value={f.service} onChange={e=>set('service',e.target.value)}><option>CORRETIVA</option><option>PREVENTIVA</option><option>INSTALAÇÃO</option><option>HIGIENIZAÇÃO</option><option>ELÉTRICA</option></select></div><div className="field">Prioridade<select value={f.priority} onChange={e=>set('priority',e.target.value)}><option value="LOW">Baixa</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select></div><div className="field">Problema relatado<textarea required minLength={3} value={f.reportedProblem} onChange={e=>set('reportedProblem',e.target.value)}/></div><button className="btn secondary" disabled={busy} onClick={()=>setStep(1)}>Voltar</button> <button className="btn" disabled={busy||f.reportedProblem.trim().length<3} onClick={createOS}>{busy?'Criando…':'Criar OS e iniciar atendimento'}</button></div>}
 {step===3&&<div className="card"><h2>3. Atendimento técnico</h2><div className="row">{[['voltage','Tensão (V)'],['current','Corrente (A)'],['returnTemperature','Temp. retorno °C'],['supplyTemperature','Temp. insuflamento °C']].map(([k,l])=><div className="field" key={k}>{l}<input className="input" type="number" onChange={e=>setF((x:any)=>({...x,measurements:{...x.measurements,[k]:e.target.value}}))}/></div>)}</div><h3>Material utilizado</h3><div className="row"><select value={f.materialId} onChange={e=>set('materialId',e.target.value)}><option value="">Nenhum</option>{materials.map(m=><option key={m.id} value={m.id}>{m.description} · estoque {m.stockQuantity}</option>)}</select><input className="input" type="number" min="0.001" step="0.001" value={f.materialQty} onChange={e=>set('materialQty',e.target.value)}/></div><OsPhotoUpload osId={created.id}/><button className="btn" disabled={busy} onClick={saveTech}>{busy?'Salvando…':'Salvar atendimento'}</button></div>}
 {step===4&&<div className="card"><h2>4. Finalização e rentabilidade</h2><div className="field">Diagnóstico técnico<textarea required minLength={3} value={f.technicalDiagnosis} onChange={e=>set('technicalDiagnosis',e.target.value)}/></div><div className="field">Serviço executado<textarea required minLength={3} value={f.performedService} onChange={e=>set('performedService',e.target.value)}/></div><div className="field">Recomendações<textarea value={f.recommendations} onChange={e=>set('recommendations',e.target.value)}/></div><div className="row">{[['finalValue','Valor cobrado'],['laborCost','Mão de obra'],['travelCost','Deslocamento'],['feesCost','Taxas'],['otherCost','Outros custos']].map(([k,l])=><div className="field" key={k}>{l}<input className="input" type="number" min="0" step="0.01" value={f[k]} onChange={e=>set(k,e.target.value)}/></div>)}</div><button className="btn" disabled={busy||f.technicalDiagnosis.trim().length<3||f.performedService.trim().length<3} onClick={complete}>{busy?'Concluindo…':'Concluir OS e calcular lucro'}</button></div>}
 </main>
}