import type {FastifyInstance} from 'fastify';
import {z} from 'zod';import {hashPortalPassword} from '../lib/portal.js';import {prisma} from '../lib/prisma.js';import {authenticate} from '../lib/auth.js';
const supplier=z.object({name:z.string().min(2),cnpj:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional().or(z.literal('')),notes:z.string().optional()});
const purchase=z.object({supplierId:z.string().uuid(),description:z.string().min(2),items:z.array(z.object({materialId:z.string().uuid(),quantity:z.number().positive(),unitCost:z.number().nonnegative()})).min(1),dueDate:z.coerce.date().optional()});
export async function closingRoutes(app:FastifyInstance){app.addHook('preHandler',authenticate);
 app.get('/portal-users',async(req:any)=>prisma.customerPortalUser.findMany({where:{companyId:req.user.companyId},select:{id:true,name:true,email:true,phone:true,active:true,lastLoginAt:true,customer:{select:{id:true,name:true}}},orderBy:{name:'asc'}}));
 app.post('/portal-users',async(req:any,reply)=>{const b=z.object({customerId:z.string().uuid(),name:z.string().min(2),email:z.string().email(),phone:z.string().optional(),password:z.string().min(8)}).safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR'}});const c=await prisma.customer.findFirst({where:{id:b.data.customerId,companyId:req.user.companyId}});if(!c)return reply.code(403).send({error:{code:'CUSTOMER_SCOPE_ERROR'}});const {password,...data}=b.data;return reply.code(201).send(await prisma.customerPortalUser.create({data:{companyId:req.user.companyId,...data,email:data.email.toLowerCase(),passwordHash:await hashPortalPassword(password)},select:{id:true,name:true,email:true,active:true}}));});
 app.get('/suppliers',async(req:any)=>prisma.supplier.findMany({where:{companyId:req.user.companyId,active:true},orderBy:{name:'asc'}}));
 app.post('/suppliers',async(req:any,reply)=>{const b=supplier.safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR'}});return reply.code(201).send(await prisma.supplier.create({data:{companyId:req.user.companyId,...b.data}}));});
 app.get('/purchases',async(req:any)=>prisma.purchaseOrder.findMany({where:{companyId:req.user.companyId},include:{supplier:true,items:{include:{material:true}}},orderBy:{createdAt:'desc'}}));
 app.post('/purchases',async(req:any,reply)=>{const b=purchase.safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR',details:b.error.flatten()}});const s=await prisma.supplier.findFirst({where:{id:b.data.supplierId,companyId:req.user.companyId}});if(!s)return reply.code(403).send({error:{code:'SUPPLIER_SCOPE_ERROR'}});const materials=await prisma.material.findMany({where:{companyId:req.user.companyId,id:{in:b.data.items.map(i=>i.materialId)}}});if(materials.length!==new Set(b.data.items.map(i=>i.materialId)).size)return reply.code(422).send({error:{code:'MATERIAL_SCOPE_ERROR'}});const total=b.data.items.reduce((a,i)=>a+i.quantity*i.unitCost,0);return reply.code(201).send(await prisma.$transaction(async tx=>{const po=await tx.purchaseOrder.create({data:{companyId:req.user.companyId,supplierId:b.data.supplierId,description:b.data.description,total,dueDate:b.data.dueDate,items:{create:b.data.items}},include:{items:true}});for(const i of b.data.items){await tx.material.update({where:{id:i.materialId},data:{stockQuantity:{increment:i.quantity},lastCost:i.unitCost}});await tx.inventoryMovement.create({data:{materialId:i.materialId,movementType:'PURCHASE',quantity:i.quantity,unitCost:i.unitCost,notes:`Compra ${po.orderNumber}`}})}return po;}));});
 app.get('/global-search',async(req:any)=>{const q=String(req.query?.q??'').trim();if(q.length<2)return {customers:[],equipment:[],orders:[],quotes:[]};const c=req.user.companyId;const [customers,equipment,orders,quotes]=await Promise.all([prisma.customer.findMany({where:{companyId:c,name:{contains:q,mode:'insensitive'}},select:{id:true,code:true,name:true},take:10}),prisma.equipment.findMany({where:{companyId:c,OR:[{assetCode:{contains:q,mode:'insensitive'}},{serialNumber:{contains:q,mode:'insensitive'}}]},select:{id:true,assetCode:true,equipmentType:true},take:10}),prisma.serviceOrder.findMany({where:{companyId:c,orderNumber:{contains:q,mode:'insensitive'}},select:{id:true,orderNumber:true,status:true},take:10}),prisma.quote.findMany({where:{companyId:c,quoteNumber:{contains:q,mode:'insensitive'}},select:{id:true,quoteNumber:true,status:true,total:true},take:10})]);return {customers,equipment,orders,quotes};});
 app.get('/readiness',async(req:any)=>{const c=req.user.companyId;const [company,templates,users,materials]=await Promise.all([prisma.companySettings.findUnique({where:{companyId:c}}),prisma.notificationTemplate.count({where:{companyId:c,active:true}}),prisma.user.count({where:{companyId:c,status:'ACTIVE'}}),prisma.material.count({where:{companyId:c,active:true}})]);return {companyConfigured:!!(company?.tradeName&&company?.legalName),brandingConfigured:!!company?.logoUrl,notificationTemplates:templates,activeUsers:users,materials,productionBlockers:[...(!company?.logoUrl?['LOGO_NOT_CONFIGURED']:[]),...(templates===0?['NOTIFICATION_TEMPLATES_EMPTY']:[])]};});
}
