import {FastifyInstance} from 'fastify';import {z} from 'zod';import {prisma} from '../lib/prisma.js';import {AuthUser} from '../lib/auth.js';import {fail} from '../lib/errors.js';
export async function managementFinanceRoutes(app:FastifyInstance){app.addHook('preHandler',async r=>r.jwtVerify());
 app.get('/payables',async req=>{const u=req.user as AuthUser;return prisma.accountPayable.findMany({where:{companyId:u.companyId},orderBy:{dueDate:'asc'}})});
 app.post('/payables',async(req,reply)=>{const u=req.user as AuthUser,p=z.object({description:z.string().min(2),amount:z.number().positive(),dueDate:z.coerce.date()}).safeParse(req.body);if(!p.success)return fail(reply,422,'VALIDATION_ERROR','Conta a pagar inválida.',p.error.flatten());return reply.code(201).send(await prisma.accountPayable.create({data:{companyId:u.companyId,...p.data}}))});
 app.post('/payables/:id/pay',async(req,reply)=>{const u=req.user as AuthUser,{id}=req.params as any;const p=z.object({paymentMethod:z.enum(['PIX','CASH','CREDIT_CARD','DEBIT_CARD','TRANSFER','BOLETO','OTHER']),paidDate:z.coerce.date().optional()}).safeParse(req.body);if(!p.success)return fail(reply,422,'VALIDATION_ERROR','Pagamento inválido.');const r=await prisma.accountPayable.updateMany({where:{id,companyId:u.companyId,status:'OPEN'},data:{status:'PAID',paidDate:p.data.paidDate??new Date(),paymentMethod:p.data.paymentMethod}});if(!r.count)return fail(reply,409,'PAYABLE_NOT_OPEN','Conta não encontrada ou já encerrada.');return {ok:true}});
 app.get('/expense-categories',async req=>{const u=req.user as AuthUser;return prisma.expenseCategory.findMany({where:{companyId:u.companyId,active:true},orderBy:{name:'asc'}})});
 app.post('/expenses',async(req,reply)=>{const u=req.user as AuthUser,p=z.object({categoryId:z.string().uuid(),serviceOrderId:z.string().uuid().optional(),description:z.string().min(2),amount:z.number().positive(),competenceDate:z.coerce.date(),dueDate:z.coerce.date().optional(),status:z.enum(['OPEN','PAID']).default('PAID'),paymentMethod:z.enum(['PIX','CASH','CREDIT_CARD','DEBIT_CARD','TRANSFER','BOLETO','OTHER']).optional()}).safeParse(req.body);if(!p.success)return fail(reply,422,'VALIDATION_ERROR','Despesa inválida.',p.error.flatten());return reply.code(201).send(await prisma.expense.create({data:{companyId:u.companyId,...p.data,paidAt:p.data.status==='PAID'?new Date():undefined}}))});
 app.get('/cash-flow',async req=>{const u=req.user as AuthUser,q=z.object({from:z.coerce.date(),to:z.coerce.date()}).parse(req.query);const [ins,outs]=await Promise.all([prisma.payment.findMany({where:{receivable:{companyId:u.companyId},paymentDate:{gte:q.from,lte:q.to}}}),prisma.expense.findMany({where:{companyId:u.companyId,status:'PAID',paidAt:{gte:q.from,lte:q.to}}})]);return {inflows:ins.map(x=>({date:x.paymentDate,amount:Number(x.amount),type:'RECEIPT'})),outflows:outs.map(x=>({date:x.paidAt,amount:Number(x.amount),type:'EXPENSE',description:x.description}))}});
 app.get('/dre',async req=>{const u=req.user as AuthUser,q=z.object({from:z.coerce.date(),to:z.coerce.date()}).parse(req.query);const [payments,expenses,orders]=await Promise.all([prisma.payment.findMany({where:{receivable:{companyId:u.companyId},paymentDate:{gte:q.from,lte:q.to}}}),prisma.expense.findMany({where:{companyId:u.companyId,status:'PAID',competenceDate:{gte:q.from,lte:q.to}},include:{category:true}}),prisma.serviceOrder.findMany({where:{companyId:u.companyId,completedAt:{gte:q.from,lte:q.to}},include:{materials:true,technicians:true}})]);const revenue=payments.reduce((s,x)=>s+Number(x.amount),0);const direct=orders.reduce((s,o)=>s+o.materials.reduce((a,m)=>a+Number(m.quantity)*Number(m.unitCost),0)+Number(o.laborCost)+o.technicians.reduce((a,t)=>a+Number(t.laborCost),0)+Number(o.travelCost)+Number(o.feesCost)+Number(o.otherCost),0);const operational=expenses.reduce((s,x)=>s+Number(x.amount),0);return {revenue,directCosts:direct,grossProfit:revenue-direct,operatingExpenses:operational,operatingResult:revenue-direct-operational,margin:revenue?Number(((revenue-direct-operational)/revenue*100).toFixed(2)):0,groups:Object.values(expenses.reduce((a:any,e)=>{a[e.category.dreGroup]=(a[e.category.dreGroup]??0)+Number(e.amount);return a},{}))}});
 app.get('/planned-vs-actual',async req=>{const u=req.user as AuthUser;const rows=await prisma.serviceOrder.findMany({where:{companyId:u.companyId,quoteId:{not:null}},include:{quote:true,materials:true,technicians:true},orderBy:{completedAt:'desc'},take:24});return rows.map(o=>{const actualCost=o.materials.reduce((a,m)=>a+Number(m.quantity)*Number(m.unitCost),0)+Number(o.laborCost)+o.technicians.reduce((a,t)=>a+Number(t.laborCost),0)+Number(o.travelCost)+Number(o.feesCost)+Number(o.otherCost);const revenue=Number(o.finalValue??0);return {orderNumber:o.orderNumber,plannedRevenue:Number(o.quote?.total??0),actualRevenue:revenue,plannedProfit:Number(o.quote?.estimatedProfit??0),actualProfit:revenue-actualCost}})});
}
