import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { authenticate } from '../lib/auth.js';

const settingsSchema=z.object({legalName:z.string().min(2),tradeName:z.string().min(2),cnpj:z.string().optional(),phone:z.string().optional(),whatsapp:z.string().optional(),email:z.string().email().optional().or(z.literal('')),website:z.string().url().optional().or(z.literal('')),pixKey:z.string().optional(),commercialTerms:z.string().optional(),warrantyTerms:z.string().optional(),quoteValidityDays:z.number().int().min(1).max(365).default(15),logoUrl:z.string().optional()});
const scheduleSchema=z.object({technicianId:z.string().uuid(),serviceOrderId:z.string().uuid().optional(),title:z.string().min(2),startsAt:z.coerce.date(),endsAt:z.coerce.date(),notes:z.string().optional()}).refine(v=>v.endsAt>v.startsAt,{message:'Horário final deve ser posterior ao inicial.'});
const planSchema=z.object({customerId:z.string().uuid(),name:z.string().min(2),frequency:z.enum(['MONTHLY','BIMONTHLY','QUARTERLY','SEMIANNUAL','ANNUAL','CUSTOM']),intervalDays:z.number().int().positive().optional(),startDate:z.coerce.date(),equipmentIds:z.array(z.string().uuid()).min(1),notes:z.string().optional()});
function nextDate(d:Date,f:string,days?:number){const x=new Date(d); const add={MONTHLY:1,BIMONTHLY:2,QUARTERLY:3,SEMIANNUAL:6,ANNUAL:12}[f as keyof object] as number|undefined;if(add)x.setMonth(x.getMonth()+add);else x.setDate(x.getDate()+(days??90));return x}
export async function operationsRoutes(app:FastifyInstance){app.addHook('preHandler',authenticate);
 app.get('/company-settings',async(req:any)=>prisma.companySettings.findUnique({where:{companyId:req.user.companyId}}));
 app.put('/company-settings',async(req:any,reply)=>{const b=settingsSchema.safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR',details:b.error.flatten().fieldErrors}});return prisma.companySettings.upsert({where:{companyId:req.user.companyId},create:{companyId:req.user.companyId,...b.data},update:b.data});});
 app.get('/technicians',async(req:any)=>prisma.user.findMany({where:{companyId:req.user.companyId,status:'ACTIVE'},select:{id:true,name:true,email:true,phone:true,role:{select:{name:true}}}}));
 app.get('/schedule',async(req:any)=>prisma.technicianSchedule.findMany({where:{companyId:req.user.companyId},include:{technician:{select:{id:true,name:true}},serviceOrder:{select:{id:true,orderNumber:true,status:true}}},orderBy:{startsAt:'asc'}}));
 app.post('/schedule',async(req:any,reply)=>{const b=scheduleSchema.safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR',details:b.error.flatten()}});const conflict=await prisma.technicianSchedule.findFirst({where:{companyId:req.user.companyId,technicianId:b.data.technicianId,status:{not:'CANCELLED'},startsAt:{lt:b.data.endsAt},endsAt:{gt:b.data.startsAt}}});if(conflict)return reply.code(409).send({error:{code:'TECHNICIAN_SCHEDULE_CONFLICT',message:'O técnico já possui atendimento neste horário.'}});return reply.code(201).send(await prisma.technicianSchedule.create({data:{companyId:req.user.companyId,...b.data}}));});
 app.get('/maintenance-plans',async(req:any)=>prisma.maintenancePlan.findMany({where:{companyId:req.user.companyId},include:{customer:true,equipment:{include:{equipment:true}},occurrences:{orderBy:{dueAt:'asc'},take:3}},orderBy:{createdAt:'desc'}}));
 app.post('/maintenance-plans',async(req:any,reply)=>{const b=planSchema.safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR',details:b.error.flatten()}});const owned=await prisma.equipment.count({where:{companyId:req.user.companyId,id:{in:b.data.equipmentIds},customerId:b.data.customerId}});if(owned!==b.data.equipmentIds.length)return reply.code(422).send({error:{code:'EQUIPMENT_SCOPE_ERROR',message:'Um ou mais equipamentos não pertencem ao cliente.'}});const first=b.data.startDate;const second=nextDate(first,b.data.frequency,b.data.intervalDays);return reply.code(201).send(await prisma.maintenancePlan.create({data:{companyId:req.user.companyId,customerId:b.data.customerId,name:b.data.name,frequency:b.data.frequency,intervalDays:b.data.intervalDays,startDate:first,notes:b.data.notes,equipment:{create:b.data.equipmentIds.map(equipmentId=>({equipmentId}))},occurrences:{create:[{dueAt:first},{dueAt:second}]}},include:{equipment:true,occurrences:true}}));});
 app.get('/maintenance-due',async(req:any)=>{const until=new Date();until.setDate(until.getDate()+30);return prisma.maintenanceOccurrence.findMany({where:{plan:{companyId:req.user.companyId,active:true},dueAt:{lte:until},status:{in:['PLANNED','DUE','OVERDUE']}},include:{plan:{include:{customer:true,equipment:{include:{equipment:true}}}}},orderBy:{dueAt:'asc'}})});
}
