import type {FastifyInstance,FastifyRequest} from 'fastify';
import {z} from 'zod';
import {prisma} from '../lib/prisma.js';
import {verifyPortalPassword,publicQuote,publicOrder} from '../lib/portal.js';

type P={portalUserId:string;companyId:string;customerId:string;kind:'customer'};
async function portalAuth(req:FastifyRequest){await req.jwtVerify();const u=req.user as P;if(u.kind!=='customer'||!u.customerId)throw new Error('PORTAL_UNAUTHORIZED');return u;}
export async function portalRoutes(app:FastifyInstance){
 app.post('/auth/login',async(req,reply)=>{const b=z.object({email:z.string().email(),password:z.string().min(6)}).safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR'}});const u=await prisma.customerPortalUser.findFirst({where:{email:b.data.email.toLowerCase(),active:true},include:{customer:true}});if(!u||!await verifyPortalPassword(b.data.password,u.passwordHash))return reply.code(401).send({error:{code:'INVALID_CREDENTIALS',message:'E-mail ou senha inválidos.'}});await prisma.customerPortalUser.update({where:{id:u.id},data:{lastLoginAt:new Date()}});const accessToken=app.jwt.sign({portalUserId:u.id,companyId:u.companyId,customerId:u.customerId,kind:'customer'},{expiresIn:'8h'});return {accessToken,user:{id:u.id,name:u.name,email:u.email,customer:{id:u.customer.id,name:u.customer.name}}};});
 app.register(async p=>{p.addHook('preHandler',portalAuth);
  p.get('/me',async(req:any)=>prisma.customerPortalUser.findUnique({where:{id:req.user.portalUserId},select:{id:true,name:true,email:true,phone:true,customer:{select:{id:true,name:true,code:true}}}}));
  p.get('/dashboard',async(req:any)=>{const c=req.user.customerId;const [equipment,openOrders,quotes,receivables,due]=await Promise.all([prisma.equipment.count({where:{customerId:c,status:'ACTIVE'}}),prisma.serviceOrder.count({where:{customerId:c,status:{notIn:['COMPLETED','RECEIVED','CANCELLED']}}}),prisma.quote.count({where:{customerId:c,status:{in:['SENT','VIEWED']}}}),prisma.accountReceivable.aggregate({where:{customerId:c,status:{in:['OPEN','PARTIALLY_PAID','OVERDUE']}},_sum:{openAmount:true}}),prisma.maintenanceOccurrence.count({where:{plan:{customerId:c,active:true},status:{in:['PLANNED','DUE','OVERDUE']}}})]);return {equipment,openOrders,pendingQuotes:quotes,openReceivables:Number(receivables._sum.openAmount??0),maintenanceDue:due};});
  p.get('/equipment',async(req:any)=>prisma.equipment.findMany({where:{customerId:req.user.customerId},select:{id:true,assetCode:true,equipmentType:true,capacityBtu:true,technology:true,status:true,serialNumber:true,unit:{select:{name:true}},environment:{select:{name:true}},model:{select:{name:true,manufacturer:{select:{name:true}}}},qr:{select:{token:true}},history:{orderBy:{occurredAt:'desc'},take:10,select:{eventType:true,description:true,occurredAt:true}}}}));
  p.get('/equipment/qr/:token',async(req:any,reply)=>{const row=await prisma.equipmentQr.findFirst({where:{token:req.params.token,active:true,equipment:{customerId:req.user.customerId}},include:{equipment:{include:{unit:true,environment:true,model:{include:{manufacturer:true}}}}}});if(!row)return reply.code(404).send({error:{code:'EQUIPMENT_NOT_FOUND'}});return row.equipment;});
  p.post('/requests',async(req:any,reply)=>{const b=z.object({unitId:z.string().uuid(),equipmentId:z.string().uuid().optional(),subject:z.string().min(3),description:z.string().min(5),preferredDate:z.coerce.date().optional()}).safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR',details:b.error.flatten()}});const unit=await prisma.customerUnit.findFirst({where:{id:b.data.unitId,customerId:req.user.customerId}});if(!unit)return reply.code(403).send({error:{code:'PORTAL_SCOPE_VIOLATION'}});return reply.code(201).send(await prisma.customerRequest.create({data:{companyId:req.user.companyId,customerId:req.user.customerId,portalUserId:req.user.portalUserId,...b.data}}));});
  p.get('/requests',async(req:any)=>prisma.customerRequest.findMany({where:{customerId:req.user.customerId},orderBy:{createdAt:'desc'}}));
  p.get('/quotes',async(req:any)=>{const rows=await prisma.quote.findMany({where:{customerId:req.user.customerId},include:{items:true},orderBy:{createdAt:'desc'}});return rows.map(publicQuote)});
  p.post('/quotes/:id/decision',async(req:any,reply)=>{const b=z.object({decision:z.enum(['APPROVE','DECLINE']),note:z.string().max(1000).optional()}).safeParse(req.body);if(!b.success)return reply.code(422).send({error:{code:'VALIDATION_ERROR'}});const q=await prisma.quote.findFirst({where:{id:req.params.id,customerId:req.user.customerId,status:{in:['SENT','VIEWED']}}});if(!q)return reply.code(404).send({error:{code:'QUOTE_NOT_AVAILABLE'}});const approved=b.data.decision==='APPROVE';return prisma.$transaction(async tx=>{const updated=await tx.quote.update({where:{id:q.id},data:{status:approved?'APPROVED':'DECLINED',approvedAt:approved?new Date():undefined,declinedAt:approved?undefined:new Date()}});await tx.customerQuoteDecision.create({data:{quoteId:q.id,customerId:req.user.customerId,portalUserId:req.user.portalUserId,decision:b.data.decision,note:b.data.note,ipAddress:req.ip,userAgent:req.headers['user-agent'],quoteSnapshot:{quoteNumber:q.quoteNumber,total:String(q.total),validUntil:q.validUntil}}});return publicQuote(updated);});});
  p.get('/service-orders',async(req:any)=>{const rows=await prisma.serviceOrder.findMany({where:{customerId:req.user.customerId},include:{equipment:{select:{assetCode:true,equipmentType:true}},statusHistory:{orderBy:{createdAt:'asc'}},photos:{select:{category:true,fileUrl:true,description:true}},signatures:true},orderBy:{createdAt:'desc'}});return rows.map(publicOrder)});
  p.get('/maintenance',async(req:any)=>prisma.maintenancePlan.findMany({where:{customerId:req.user.customerId,active:true},include:{equipment:{include:{equipment:{select:{id:true,assetCode:true,equipmentType:true,capacityBtu:true}}}},occurrences:{orderBy:{dueAt:'asc'}}}}));
  p.get('/documents',async(req:any)=>{const ids=[...(await prisma.quote.findMany({where:{customerId:req.user.customerId},select:{id:true}})).map(x=>x.id),...(await prisma.serviceOrder.findMany({where:{customerId:req.user.customerId},select:{id:true}})).map(x=>x.id)];return prisma.generatedDocument.findMany({where:{companyId:req.user.companyId,entityId:{in:ids}},select:{id:true,type:true,entityId:true,publicToken:true,expiresAt:true,createdAt:true},orderBy:{createdAt:'desc'}})});
  p.get('/finance',async(req:any)=>prisma.accountReceivable.findMany({where:{customerId:req.user.customerId},include:{payments:true},orderBy:{dueDate:'desc'}}));
  p.get('/notifications',async(req:any)=>prisma.notification.findMany({where:{companyId:req.user.companyId,OR:[{recipient:(await prisma.customer.findUnique({where:{id:req.user.customerId},select:{email:true}}))?.email??'__none__'},{metadata:{path:['customerId'],equals:req.user.customerId}}]},select:{id:true,eventType:true,channel:true,status:true,subject:true,body:true,createdAt:true,readAt:true},orderBy:{createdAt:'desc'},take:100}));
 });
}
