import {FastifyInstance} from 'fastify';import {z} from 'zod';import {prisma} from '../lib/prisma.js';import {AuthUser} from '../lib/auth.js';import {fail} from '../lib/errors.js';import {quoteTotals} from '../lib/commercial.js';
const item=z.object({itemType:z.enum(['SERVICE','MATERIAL','OTHER']),serviceId:z.string().uuid().optional(),materialId:z.string().uuid().optional(),description:z.string().min(2),quantity:z.number().positive(),unitPrice:z.number().nonnegative(),unitCost:z.number().nonnegative()});
const create=z.object({customerId:z.string().uuid(),unitId:z.string().uuid().optional(),validUntil:z.coerce.date().optional(),paymentTerms:z.string().optional(),warrantyTerms:z.string().optional(),notes:z.string().optional(),discount:z.number().nonnegative().default(0),items:z.array(item).min(1)});
export async function quoteRoutes(app:FastifyInstance){app.addHook('preHandler',async r=>r.jwtVerify());
app.get('/',async req=>{const u=req.user as AuthUser;return prisma.quote.findMany({where:{companyId:u.companyId},include:{customer:true,unit:true,items:true},orderBy:{createdAt:'desc'}})});
app.get('/:id',async(req,reply)=>{const u=req.user as AuthUser,{id}=req.params as any;const q=await prisma.quote.findFirst({where:{id,companyId:u.companyId},include:{customer:true,unit:true,items:true,serviceOrders:true,receivables:{include:{payments:true}}}});return q??fail(reply,404,'QUOTE_NOT_FOUND','Orçamento não encontrado.')});
app.post('/',async(req,reply)=>{const u=req.user as AuthUser,p=create.safeParse(req.body);if(!p.success)return fail(reply,422,'VALIDATION_ERROR','Orçamento inválido.',p.error.flatten());const customer=await prisma.customer.findFirst({where:{id:p.data.customerId,companyId:u.companyId}});if(!customer)return fail(reply,404,'CUSTOMER_NOT_FOUND','Cliente não encontrado.');if(p.data.unitId){const unit=await prisma.customerUnit.findFirst({where:{id:p.data.unitId,customerId:customer.id}});if(!unit)return fail(reply,422,'UNIT_CUSTOMER_MISMATCH','Unidade não pertence ao cliente.')}const count=await prisma.quote.count({where:{companyId:u.companyId}});const totals=quoteTotals(p.data.items,p.data.discount);const q=await prisma.quote.create({data:{companyId:u.companyId,quoteNumber:`ORC-${String(count+1).padStart(6,'0')}`,customerId:p.data.customerId,unitId:p.data.unitId,validUntil:p.data.validUntil,paymentTerms:p.data.paymentTerms,warrantyTerms:p.data.warrantyTerms,notes:p.data.notes,discount:p.data.discount,...totals,createdById:u.id,items:{create:p.data.items}},include:{items:true,customer:true}});return reply.code(201).send(q)});
app.post('/:id/send',async(req,reply)=>{const u=req.user as AuthUser,{id}=req.params as any;const q=await prisma.quote.findFirst({where:{id,companyId:u.companyId}});if(!q)return fail(reply,404,'QUOTE_NOT_FOUND','Orçamento não encontrado.');if(q.status!=='DRAFT')return fail(reply,409,'INVALID_QUOTE_STATUS','Somente orçamento em rascunho pode ser enviado.');return prisma.quote.update({where:{id},data:{status:'SENT',sentAt:new Date()}})});
app.post('/:id/approve',async(req,reply)=>{const u=req.user as AuthUser,{id}=req.params as any;const q=await prisma.quote.findFirst({where:{id,companyId:u.companyId}});if(!q)return fail(reply,404,'QUOTE_NOT_FOUND','Orçamento não encontrado.');if(!['SENT','VIEWED'].includes(q.status))return fail(reply,409,'INVALID_QUOTE_STATUS','Orçamento precisa estar enviado ou visualizado.');if(q.validUntil&&q.validUntil<new Date())return fail(reply,409,'QUOTE_EXPIRED','Orçamento vencido.');return prisma.quote.update({where:{id},data:{status:'APPROVED',approvedAt:new Date()}})});
app.post('/:id/convert-to-service-order',async(req,reply)=>{const u=req.user as AuthUser,{id}=req.params as any;const body=z.object({reportedProblem:z.string().min(3).default('Serviço conforme orçamento aprovado'),environmentId:z.string().uuid().optional(),equipmentId:z.string().uuid().optional(),scheduledAt:z.coerce.date().optional()}).safeParse(req.body??{});if(!body.success)return fail(reply,422,'VALIDATION_ERROR','Dados de conversão inválidos.',body.error.flatten());try{const result=await prisma.$transaction(async tx=>{const q=await tx.quote.findFirst({where:{id,companyId:u.companyId},include:{items:true}});if(!q)throw new Error('NOT_FOUND');if(q.status!=='APPROVED')throw new Error('NOT_APPROVED');if(!q.unitId)throw new Error('UNIT_REQUIRED');if(q.convertedAt)throw new Error('ALREADY_CONVERTED');const count=await tx.serviceOrder.count({where:{companyId:u.companyId}});const os=await tx.serviceOrder.create({data:{companyId:u.companyId,orderNumber:`OS-${String(count+1).padStart(6,'0')}`,customerId:q.customerId,unitId:q.unitId,environmentId:body.data.environmentId,equipmentId:body.data.equipmentId,priority:'NORMAL',status:body.data.scheduledAt?'SCHEDULED':'OPEN',reportedProblem:body.data.reportedProblem,scheduledAt:body.data.scheduledAt,quotedValue:q.total,finalValue:q.total,createdById:u.id,quoteId:q.id,statusHistory:{create:{newStatus:body.data.scheduledAt?'SCHEDULED':'OPEN',userId:u.id}}}});await tx.quote.update({where:{id:q.id},data:{convertedAt:new Date()}});return os});return reply.code(201).send(result)}catch(e:any){const map:any={NOT_FOUND:['QUOTE_NOT_FOUND','Orçamento não encontrado.'],NOT_APPROVED:['QUOTE_NOT_APPROVED','Aprovação é obrigatória antes da conversão.'],UNIT_REQUIRED:['UNIT_REQUIRED','Informe a unidade do cliente.'],ALREADY_CONVERTED:['QUOTE_ALREADY_CONVERTED','Este orçamento já foi convertido.']};const x=map[e.message];return x?fail(reply,e.message==='NOT_FOUND'?404:409,x[0],x[1]):fail(reply,500,'CONVERSION_ERROR','Não foi possível converter o orçamento.')}});
}
