import { prisma } from './prisma.js';
export type EventType='QUOTE_SENT'|'QUOTE_APPROVED'|'MAINTENANCE_DUE'|'APPOINTMENT_SCHEDULED'|'TECHNICIAN_ON_THE_WAY'|'SERVICE_ORDER_COMPLETED'|'RECEIVABLE_CREATED'|'PAYMENT_RECEIVED'|'RECEIPT_ISSUED';
type Ctx={companyId:string,eventType:EventType,entityType?:string,entityId?:string,recipient:{name?:string,whatsapp?:string,email?:string},vars:Record<string,string|number|undefined>};
const defaults:Record<EventType,{subject:string,body:string}>={
 QUOTE_SENT:{subject:'Seu orçamento Solucenter {{number}}',body:'Olá {{name}}, seu orçamento {{number}} no valor de {{value}} está disponível: {{link}}'},
 QUOTE_APPROVED:{subject:'Orçamento aprovado',body:'Orçamento {{number}} aprovado com sucesso.'},
 MAINTENANCE_DUE:{subject:'Manutenção preventiva próxima',body:'Olá {{name}}, a manutenção preventiva {{plan}} está prevista para {{date}}.'},
 APPOINTMENT_SCHEDULED:{subject:'Atendimento agendado',body:'Olá {{name}}, seu atendimento Solucenter foi agendado para {{date}}.'},
 TECHNICIAN_ON_THE_WAY:{subject:'Técnico a caminho',body:'Olá {{name}}, o técnico {{technician}} está a caminho para seu atendimento {{number}}.'},
 SERVICE_ORDER_COMPLETED:{subject:'Serviço concluído',body:'Olá {{name}}, a OS {{number}} foi concluída. Relatório: {{link}}'},
 RECEIVABLE_CREATED:{subject:'Cobrança Solucenter',body:'Olá {{name}}, foi gerada uma cobrança de {{value}}, vencimento {{date}}. {{link}}'},
 PAYMENT_RECEIVED:{subject:'Pagamento recebido',body:'Recebemos seu pagamento de {{value}}. Saldo em aberto: {{balance}}.'},
 RECEIPT_ISSUED:{subject:'Recibo Solucenter',body:'Olá {{name}}, seu recibo está disponível: {{link}}'}
};
function render(t:string,v:Ctx['vars']){return t.replace(/{{(\w+)}}/g,(_,k)=>String(v[k]??''));}
export async function emitNotificationEvent(c:Ctx){
 const templates=await prisma.notificationTemplate.findMany({where:{companyId:c.companyId,eventType:c.eventType,active:true}});
 const channels=templates.length?templates.map(t=>({channel:t.channel,subject:t.subject??defaults[c.eventType].subject,body:t.body})):[
  ...(c.recipient.whatsapp?[{channel:'WHATSAPP' as const,...defaults[c.eventType]}]:[]),...(c.recipient.email?[{channel:'EMAIL' as const,...defaults[c.eventType]}]:[])
 ];
 for(const x of channels){const recipient=x.channel==='WHATSAPP'?c.recipient.whatsapp:c.recipient.email;if(!recipient)continue;await prisma.notification.create({data:{companyId:c.companyId,eventType:c.eventType,channel:x.channel,recipient,recipientName:c.recipient.name,subject:render(x.subject,c.vars),body:render(x.body,c.vars),entityType:c.entityType,entityId:c.entityId,metadata:c.vars}})}
}
async function sendWhatsApp(to:string,body:string){const token=process.env.WHATSAPP_ACCESS_TOKEN,phone=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!phone)throw new Error('WHATSAPP_NOT_CONFIGURED');const r=await fetch(`https://graph.facebook.com/${process.env.WHATSAPP_GRAPH_VERSION??'v23.0'}/${phone}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body}})});const j=await r.json();if(!r.ok)throw new Error(JSON.stringify(j));return j;}
async function sendEmail(to:string,subject:string,body:string){const key=process.env.EMAIL_API_KEY,from=process.env.EMAIL_FROM;if(!key||!from)throw new Error('EMAIL_NOT_CONFIGURED');const endpoint=process.env.EMAIL_API_URL??'https://api.resend.com/emails';const r=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,text:body})});const j=await r.json();if(!r.ok)throw new Error(JSON.stringify(j));return j;}
export async function processNotificationQueue(limit=25){const now=new Date();const rows=await prisma.notification.findMany({where:{status:'PENDING',scheduledAt:{lte:now},OR:[{nextAttemptAt:null},{nextAttemptAt:{lte:now}}]},orderBy:{createdAt:'asc'},take:limit});let sent=0,failed=0;for(const n of rows){const attempt=n.attempts+1;await prisma.notification.update({where:{id:n.id},data:{status:'PROCESSING',attempts:attempt}});try{const res=n.channel==='WHATSAPP'?await sendWhatsApp(n.recipient,n.body):n.channel==='EMAIL'?await sendEmail(n.recipient,n.subject??'Solucenter',n.body):{ok:true};const provider=n.channel==='WHATSAPP'?'META_WHATSAPP':n.channel==='EMAIL'?'EMAIL_HTTP':'IN_APP';await prisma.$transaction([prisma.notificationDelivery.create({data:{notificationId:n.id,attempt,provider,status:'SENT',responsePayload:res as any}}),prisma.notification.update({where:{id:n.id},data:{status:'SENT',sentAt:new Date(),provider,lastError:null}})]);sent++;}catch(e:any){const terminal=attempt>=n.maxAttempts;const next=new Date(Date.now()+Math.min(60,2**attempt)*60000);await prisma.$transaction([prisma.notificationDelivery.create({data:{notificationId:n.id,attempt,provider:n.channel,errorMessage:String(e.message),status:'FAILED'}}),prisma.notification.update({where:{id:n.id},data:{status:terminal?'FAILED':'PENDING',lastError:String(e.message),nextAttemptAt:terminal?null:next}})]);failed++;}}return {processed:rows.length,sent,failed};}
