import {randomUUID} from 'node:crypto';
import type {FastifyInstance} from 'fastify';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
const database=process.env.TEST_DATABASE_URL;
if(database){const url=new URL(database);if(!['localhost','127.0.0.1'].includes(url.hostname)||!url.pathname.includes('solucenter_test'))throw new Error('Integration tests require a disposable local solucenter_test database');process.env.DATABASE_URL=database}
describe.skipIf(!database)('PostgreSQL: customer registration through equipment QR',()=>{
 let app:FastifyInstance,db:typeof import('../src/lib/prisma.js').prisma,token:string,foreignToken:string,companyId:string;
 async function call(method:'GET'|'POST',path:string,payload?:object,access=token){return app.inject({method,url:'/api/v1'+path,payload,headers:{authorization:`Bearer ${access}`}})}
 beforeAll(async()=>{db=(await import('../src/lib/prisma.js')).prisma;const company=await db.company.create({data:{tradeName:'Registration Integration'}});companyId=company.id;const foreign=await db.company.create({data:{tradeName:'Foreign Registration'}});app=(await import('../src/server.js')).buildApp();await app.ready();token=app.jwt.sign({id:randomUUID(),companyId,role:'ADMIN',permissions:[]});foreignToken=app.jwt.sign({id:randomUUID(),companyId:foreign.id,role:'ADMIN',permissions:[]})},30000);
 it('creates customer and first unit atomically, then environment, equipment and QR files',async()=>{const cpfCnpj=`T-${randomUUID()}`;const created=await call('POST','/customers',{type:'PJ',name:'Cliente Cadastro Completo',tradeName:'Cliente Teste',cpfCnpj,phone:'8300000000',whatsapp:'83999999999',email:'teste@example.com',firstUnit:{name:'Matriz',cep:'58400000',street:'Rua Teste',number:'10',neighborhood:'Centro',city:'Campina Grande',state:'pb'}});expect(created.statusCode).toBe(201);const customer=created.json();expect(customer.units).toHaveLength(1);expect(customer.units[0]).toMatchObject({name:'Matriz',state:'PB'});const unit=customer.units[0];const environment=await call('POST',`/units/${unit.id}/environments`,{name:'Sala técnica'});expect(environment.statusCode).toBe(201);const equipment=await call('POST','/equipment',{customerId:customer.id,unitId:unit.id,environmentId:environment.json().id,equipmentType:'SPLIT',capacityBtu:9000});expect(equipment.statusCode).toBe(201);const saved=equipment.json();expect((await call('GET',`/equipment/by-qr/${saved.qr.token}`)).statusCode).toBe(200);expect((await call('GET',`/equipment/by-qr/${saved.qr.token}`,undefined,foreignToken)).statusCode).toBe(404);const pdf=await call('GET',`/equipment/${saved.id}/label`);expect(pdf.statusCode).toBe(200);expect(pdf.rawPayload.subarray(0,4).toString()).toBe('%PDF');const png=await call('GET',`/equipment/${saved.id}/qr`);expect(png.statusCode).toBe(200);expect(png.rawPayload.subarray(1,4).toString()).toBe('PNG')},30000);
 it('does not leave a customer when the first unit is invalid',async()=>{const name=`Invalid ${randomUUID()}`;const response=await call('POST','/customers',{type:'PJ',name,firstUnit:{name:'X',state:'PARAIBA'}});expect(response.statusCode).toBe(422);expect(await db.customer.count({where:{companyId,name}})).toBe(0)});
 it('normalizes blank unique fields and blocks duplicate documents and foreign reads',async()=>{for(const suffix of ['A','B'])expect((await call('POST','/customers',{type:'PF',name:`Sem documento ${suffix}`,cpfCnpj:'',email:''})).statusCode).toBe(201);const document=`CPF-${randomUUID()}`;const first=await call('POST','/customers',{type:'PF',name:'Documento único',cpfCnpj:document});expect(first.statusCode).toBe(201);expect((await call('POST','/customers',{type:'PF',name:'Documento repetido',cpfCnpj:document})).statusCode).toBe(409);expect((await call('GET',`/customers/${first.json().id}`,undefined,foreignToken)).statusCode).toBe(404);expect((await call('GET',`/units/customer/${first.json().id}`,undefined,foreignToken)).statusCode).toBe(404)});
 afterAll(async()=>{await app?.close();await db?.$disconnect()});
});
