import {randomUUID} from 'node:crypto';
import type {FastifyInstance} from 'fastify';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
const database=process.env.TEST_DATABASE_URL;
if(database){const url=new URL(database);if(!['localhost','127.0.0.1'].includes(url.hostname)||!url.pathname.includes('solucenter_test'))throw new Error('Integration tests require a disposable local solucenter_test database');process.env.DATABASE_URL=database}
describe.skipIf(!database)('PostgreSQL: public equipment QR',()=>{
 let app:FastifyInstance,db:typeof import('../src/lib/prisma.js').prisma,token:string,qrToken:string,equipmentId:string,companyId:string;
 beforeAll(async()=>{db=(await import('../src/lib/prisma.js')).prisma;const company=await db.company.create({data:{tradeName:'QR Integration Test'}});companyId=company.id;const customer=await db.customer.create({data:{companyId,code:randomUUID(),name:'Private customer',type:'PJ',phone:'83999999999'}});const unit=await db.customerUnit.create({data:{customerId:customer.id,name:'Matriz',street:'Private street'}});const environment=await db.environment.create({data:{unitId:unit.id,name:'Sala técnica'}});qrToken=randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','').slice(0,16);const equipment=await db.equipment.create({data:{companyId,customerId:customer.id,unitId:unit.id,environmentId:environment.id,assetCode:`SC-${randomUUID()}`,equipmentType:'SPLIT',capacityBtu:9000,technology:'INVERTER',voltage:220,refrigerant:'R32',qr:{create:{token:qrToken}}}});equipmentId=equipment.id;app=(await import('../src/server.js')).buildApp();await app.ready();token=app.jwt.sign({id:randomUUID(),companyId,role:'ADMIN',permissions:[]})},30000);
 it('opens the correct minimal public record and hides private customer data',async()=>{const r=await app.inject({method:'GET',url:`/public/equipment/${qrToken}`});expect(r.statusCode).toBe(200);expect(r.headers['cache-control']).toBe('no-store');expect(r.json()).toMatchObject({company:{name:'QR Integration Test'},equipment:{assetCode:expect.any(String),equipmentType:'SPLIT',capacityBtu:9000,unit:'Matriz',environment:'Sala técnica'}});expect(JSON.stringify(r.json())).not.toContain('Private customer');expect(JSON.stringify(r.json())).not.toContain('Private street');expect(JSON.stringify(r.json())).not.toContain('83999999999')});
 it('generates real PNG/PDF files only for the owning company',async()=>{const headers={authorization:`Bearer ${token}`};const png=await app.inject({method:'GET',url:`/api/v1/equipment/${equipmentId}/qr`,headers});expect(png.statusCode).toBe(200);expect(png.headers['content-type']).toContain('image/png');expect(png.rawPayload.subarray(1,4).toString()).toBe('PNG');const pdf=await app.inject({method:'GET',url:`/api/v1/equipment/${equipmentId}/label.pdf`,headers});expect(pdf.statusCode).toBe(200);expect(pdf.headers['content-type']).toContain('application/pdf');expect(pdf.rawPayload.subarray(0,4).toString()).toBe('%PDF');const foreign=app.jwt.sign({id:randomUUID(),companyId:randomUUID(),role:'ADMIN',permissions:[]});expect((await app.inject({method:'GET',url:`/api/v1/equipment/${equipmentId}/label.pdf`,headers:{authorization:`Bearer ${foreign}`}})).statusCode).toBe(404)});
 it('does not reveal malformed, unknown or revoked tokens',async()=>{for(const value of ['invalid',randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','').slice(0,16)])expect((await app.inject({method:'GET',url:`/public/equipment/${value}`})).statusCode).toBe(404);await db.equipmentQr.update({where:{token:qrToken},data:{active:false,revokedAt:new Date()}});expect((await app.inject({method:'GET',url:`/public/equipment/${qrToken}`})).statusCode).toBe(404)});
 afterAll(async()=>{await app?.close();await db?.$disconnect()});
});
